In [ ]:
defination >> numpy is an general purpose processing package that provides the high performance multidimensional array objects & tools for wrokking with arrays. 
it is the fundamental for scientific computing in python.

In [3]:
import numpy as np
# One Dimensional Array
lst = [1,2,3,34,45,4]
arr = np.array(lst) 
type(arr)

numpy.ndarray

In [4]:
print(arr) # this is the form of array printing

[ 1  2  3 34 45  4]


In [5]:
print(lst) # this is the form of list printing

[1, 2, 3, 34, 45, 4]


In [6]:
arr.shape # this tells us that it is an one or multidimensional array

(6,)

In [ ]:
# Multi-Nested Array

In [9]:
lst1 = [1,2,38,34,45,44]
lst2 = [13,2,33,34,45,4]
lst3 = [1,22,3,34,45,44]
arr = np.array([lst1,lst2,lst3]) # using this command we are converting the list into array

In [10]:
arr # Its an 2D array

array([[ 1,  2, 38, 34, 45, 44],
       [13,  2, 33, 34, 45,  4],
       [ 1, 22,  3, 34, 45, 44]])

In [12]:
arr.shape # this shows both rows and columns it means it is an multiidimensional arrays

(3, 6)

In [15]:
arr.reshape(6,3) # the command to reshape the array corresponds with rows and columns without changing its data tyoe

array([[ 1,  2, 38],
       [34, 45, 44],
       [13,  2, 33],
       [34, 45,  4],
       [ 1, 22,  3],
       [34, 45, 44]])

In [ ]:
# Indexing is Numpy Array

In [18]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [21]:
arr[3] # this prints the value inside the array on index 3 that is 4 here

np.int64(4)

In [ ]:
# Indexing in 2D Array 

In [4]:
import numpy as np
lst1 = [1,2,38,34,45,44]
lst2 = [13,2,33,34,45,4]
lst3 = [1,22,3,34,45,44]
arr = np.array([lst1,lst2,lst3])
arr

array([[ 1,  2, 38, 34, 45, 44],
       [13,  2, 33, 34, 45,  4],
       [ 1, 22,  3, 34, 45, 44]])

In [5]:
arr[:,:] # prints whole indexing 

array([[ 1,  2, 38, 34, 45, 44],
       [13,  2, 33, 34, 45,  4],
       [ 1, 22,  3, 34, 45, 44]])

In [11]:
arr[1:,1:] # to print particular index row or column

array([[ 2, 33, 34, 45,  4],
       [22,  3, 34, 45, 44]])

In [16]:
# built in fucntions in array 
arr = np.arange(0,10) # this provides the number from 0 to 9 means 10 numbers
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr = np.arange(0,10,step=2) # this step=2 provides the numbers in the gap of 2 numbers
arr

array([0, 2, 4, 6, 8])

In [20]:
arr = np.linspace(0,10,20)
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [21]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [23]:
arr[3:]=100 # this will add or copy the 100 number from 3rd to 5th index this called as copy and broadcasting
arr  

array([  1,   2,   3, 100, 100, 100])

In [24]:
arr1 = arr # here we have assigned an arr to arr1 
arr1

array([  1,   2,   3, 100, 100, 100])

In [26]:
arr1[1:]=500
arr1

array([  1, 500, 500, 500, 500, 500])

In [28]:
arr2 = arr1
arr2

array([  1, 500, 500, 500, 500, 500])

In [30]:
arr2[2:]=1000
arr2

array([   1,  500, 1000, 1000, 1000, 1000])

In [ ]:
# Conditions Useful in EDA

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr
val = 2
arr<2

array([ True, False, False, False, False, False])

In [4]:
print(arr*2)

[ 2  4  6  8 10 12]


In [5]:
print(arr[arr<2])

[1]


In [6]:
print(arr[arr>2])

[3 4 5 6]


In [7]:
# function Ones()
np.ones(5) # this willl creates the array of 5 (1's) with (.) cause it is an defaultype in float

array([1., 1., 1., 1., 1.])

In [12]:
np.ones(2,dtype=int) # we can also set the dtype

array([1, 1])

In [14]:
np.ones((2,5),dtype=float) # to have the rows and columns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.random.rand(3,3) # this will prints the  values between only 0 to 1 cause it is an uniform distribution

array([[0.86686831, 0.82779184, 0.28199924],
       [0.90443087, 0.8145158 , 0.83169448],
       [0.69472339, 0.79940397, 0.39969424]])

In [22]:
np.random.rand(4,4) 

array([[0.35493836, 0.19513136, 0.83824507, 0.96213328],
       [0.71045551, 0.55550735, 0.07187236, 0.06281518],
       [0.35117032, 0.65134166, 0.51219231, 0.94233634],
       [0.58764009, 0.88290878, 0.81851051, 0.70318539]])

In [24]:
np.random.randint(0,100,8).reshape(2,4)

array([[26, 67,  6, 37],
       [76, 71, 88,  3]], dtype=int32)

In [31]:
np.random.randint((1,5)).reshape(1,2)

array([[0, 4]], dtype=int32)